/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_SPACEXPANSEWALLETRPCSERVERSTUB_H_
#define JSONRPC_CPP_STUB_SPACEXPANSEWALLETRPCSERVERSTUB_H_

#include <jsonrpccpp/server.h>

class SpaceXpanseWalletRpcServerStub : public jsonrpc::AbstractServer<SpaceXpanseWalletRpcServerStub>
{
    public:
        SpaceXpanseWalletRpcServerStub(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<SpaceXpanseWalletRpcServerStub>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("getaddressinfo", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "address",jsonrpc::JSON_STRING, NULL), &SpaceXpanseWalletRpcServerStub::getaddressinfoI);
            this->bindAndAddMethod(jsonrpc::Procedure("signmessage", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_STRING, "address",jsonrpc::JSON_STRING,"message",jsonrpc::JSON_STRING, NULL), &SpaceXpanseWalletRpcServerStub::signmessageI);
            this->bindAndAddMethod(jsonrpc::Procedure("name_update", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_STRING, "name",jsonrpc::JSON_STRING,"value",jsonrpc::JSON_STRING, NULL), &SpaceXpanseWalletRpcServerStub::name_updateI);
        }

        inline virtual void getaddressinfoI(const Json::Value &request, Json::Value &response)
        {
            response = this->getaddressinfo(request["address"].asString());
        }
        inline virtual void signmessageI(const Json::Value &request, Json::Value &response)
        {
            response = this->signmessage(request["address"].asString(), request["message"].asString());
        }
        inline virtual void name_updateI(const Json::Value &request, Json::Value &response)
        {
            response = this->name_update(request["name"].asString(), request["value"].asString());
        }
        virtual Json::Value getaddressinfo(const std::string& address) = 0;
        virtual std::string signmessage(const std::string& address, const std::string& message) = 0;
        virtual std::string name_update(const std::string& name, const std::string& value) = 0;
};

#endif //JSONRPC_CPP_STUB_SPACEXPANSEWALLETRPCSERVERSTUB_H_
