/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_SPACEXPANSERPCSERVERSTUB_H_
#define JSONRPC_CPP_STUB_SPACEXPANSERPCSERVERSTUB_H_

#include <jsonrpccpp/server.h>

class SpaceXpanseRpcServerStub : public jsonrpc::AbstractServer<SpaceXpanseRpcServerStub>
{
    public:
        SpaceXpanseRpcServerStub(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<SpaceXpanseRpcServerStub>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("getzmqnotifications", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_ARRAY,  NULL), &SpaceXpanseRpcServerStub::getzmqnotificationsI);
            this->bindAndAddNotification(jsonrpc::Procedure("trackedgames", jsonrpc::PARAMS_BY_NAME, "command",jsonrpc::JSON_STRING,"gameid",jsonrpc::JSON_STRING, NULL), &SpaceXpanseRpcServerStub::trackedgamesI);
            this->bindAndAddMethod(jsonrpc::Procedure("getnetworkinfo", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &SpaceXpanseRpcServerStub::getnetworkinfoI);
            this->bindAndAddMethod(jsonrpc::Procedure("getblockchaininfo", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT,  NULL), &SpaceXpanseRpcServerStub::getblockchaininfoI);
            this->bindAndAddMethod(jsonrpc::Procedure("getblockhash", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_STRING, "height",jsonrpc::JSON_INTEGER, NULL), &SpaceXpanseRpcServerStub::getblockhashI);
            this->bindAndAddMethod(jsonrpc::Procedure("getblockheader", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "blockhash",jsonrpc::JSON_STRING, NULL), &SpaceXpanseRpcServerStub::getblockheaderI);
            this->bindAndAddMethod(jsonrpc::Procedure("game_sendupdates", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "fromblock",jsonrpc::JSON_STRING,"gameid",jsonrpc::JSON_STRING, NULL), &SpaceXpanseRpcServerStub::game_sendupdatesI);
            this->bindAndAddMethod(jsonrpc::Procedure("verifymessage", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "address",jsonrpc::JSON_STRING,"message",jsonrpc::JSON_STRING,"signature",jsonrpc::JSON_STRING, NULL), &SpaceXpanseRpcServerStub::verifymessageI);
            this->bindAndAddMethod(jsonrpc::Procedure("getrawmempool", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_ARRAY,  NULL), &SpaceXpanseRpcServerStub::getrawmempoolI);
        }

        inline virtual void getzmqnotificationsI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getzmqnotifications();
        }
        inline virtual void trackedgamesI(const Json::Value &request)
        {
            this->trackedgames(request["command"].asString(), request["gameid"].asString());
        }
        inline virtual void getnetworkinfoI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getnetworkinfo();
        }
        inline virtual void getblockchaininfoI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getblockchaininfo();
        }
        inline virtual void getblockhashI(const Json::Value &request, Json::Value &response)
        {
            response = this->getblockhash(request["height"].asInt());
        }
        inline virtual void getblockheaderI(const Json::Value &request, Json::Value &response)
        {
            response = this->getblockheader(request["blockhash"].asString());
        }
        inline virtual void game_sendupdatesI(const Json::Value &request, Json::Value &response)
        {
            response = this->game_sendupdates(request["fromblock"].asString(), request["gameid"].asString());
        }
        inline virtual void verifymessageI(const Json::Value &request, Json::Value &response)
        {
            response = this->verifymessage(request["address"].asString(), request["message"].asString(), request["signature"].asString());
        }
        inline virtual void getrawmempoolI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->getrawmempool();
        }
        virtual Json::Value getzmqnotifications() = 0;
        virtual void trackedgames(const std::string& command, const std::string& gameid) = 0;
        virtual Json::Value getnetworkinfo() = 0;
        virtual Json::Value getblockchaininfo() = 0;
        virtual std::string getblockhash(int height) = 0;
        virtual Json::Value getblockheader(const std::string& blockhash) = 0;
        virtual Json::Value game_sendupdates(const std::string& fromblock, const std::string& gameid) = 0;
        virtual Json::Value verifymessage(const std::string& address, const std::string& message, const std::string& signature) = 0;
        virtual Json::Value getrawmempool() = 0;
};

#endif //JSONRPC_CPP_STUB_SPACEXPANSERPCSERVERSTUB_H_
